### ISSUE TITLE
No "*.cyclonedds.compilers.Idlc" found under the command "make datatype"

### ISSUE THREAD

**Issue by qqqshengwei** [eclipse/cyclonedds#14]
By reading the document "VortexDDS Release 0.1.0"， I tried to translate "HelloWorldData.idl" into "HelloWorldData.c" and "HelloWorldData.h" with the command “make datatype” in the directory "*/examples/helloworld". However, error came with the msg "Could not find or load main class org.eclipse.cyclonedds.compilers.Idlc". Where can I get this "*.Idlc". Thx!

**Comment by eboasson** [comment]
Hi,

Did you build CycloneDDS as described in the README? The class file is generated as part of building CycloneDDS. The examples then also get built, by the way.

Apologies for the discrepancy between that document and the repository. It seems that document describes installing a binary package, whereas cloning this repository only gets you source code.

**Comment by qqqshengwei** [comment]
Thank you for your reply. Yes, I have done the installation as described in the README and it works right. Nevertheless, I wonder if I can translate the files "*.idl" individually via something like "*.cyclonedds.compilers.Idlc" in cyclonedds. Could you help me?

**Comment by eboasson** [comment]
The easiest way is to use the `dds_idlc` script in the `idlc` subdirectory of your build, which simply runs java with the classpath set correctly:

```
java -classpath "/XYZ/cyclonedds/build/idlc/target/idlc-jar-with-dependencies.jar" org.eclipse.cyclonedds.compilers.Idlc "$@"
```

Just give it the IDL file as an argument

**Comment by qqqshengwei** [comment]
It works. It is very nice of you.  I am curious about the role of idl in Cyclonedds. ^_^

**Comment by eboasson** [comment]
IDL is used in DDS (in all DDS implementations, not just in Cyclone DDS) to define the data types read and written by the application. Having full type information available makes it possible to do queries and filtering on data, type checking between readers and writers, low-overhead wire formats with automatic conversion between little- and big-endian machines, tools that can display any data without requiring metadata on each sample, etc.

The reason IDL is used and not some other language for defining these types is that IDL was available and the language of choice for this at the OMG (where DDS was standardised) and that it had mappings defined to various programming languages, defining how a certain type definition in IDL shows up in C, C++, Java, ... And of course, many of the formats now commonly used for data exchange or data type definitions didn't even exist 15 years ago!

**Comment by qqqshengwei** [comment]
I am very grateful for your help. I have read the "OMG IDL Specification". This way of language mapping is very interesting.  Is this tool "org.eclipse.cyclonedds.compilers.Idlc" open source? And, can it be independent from dds or even extended independently? I wonder if I could map data definition of IDL into that of JAVA.
