### ISSUE TITLE
Some questions about how to make the size of libddsc.so smaller

### ISSUE THREAD

**Issue by jwcesign** [eclipse/cyclonedds#28]
Hi, recently, I want to make the size of  `libddsc.so` smaller, because my hardware has very small RAM size, just `3M`; and `libddsc.so` contains all the files in ddsc and the files in ddsi directory, when the example runs, the libddsc.so will be loaded into the RAM, so will take over `1M`(I want it smaller than `1M`). When I check the `/proc/$PID/smap`, I get the key information below:
~~~
7fab8631b000-7fab8640b000 r-xp 00000000 fd:02 3939856                    cyclonedds/build/lib/libddsc.so.0.1.0
Size:                960 kB
Rss:                 916 kB
Pss:                 480 kB
Shared_Clean:        872 kB
Shared_Dirty:          0 kB
Private_Clean:        44 kB
Private_Dirty:         0 kB
Referenced:          916 kB
Anonymous:             0 kB
AnonHugePages:         0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Locked:                0 kB
VmFlags: rd ex mr mw me 
~~~
 This lib costs about `916KB`, So how can I make libddsc.so smaller to make the example take less RAM?

**Comment by jwcesign** [comment]
And `q_config`, `q_entity` and `q_plist` cost about 500KB.

**Comment by jwcesign** [comment]
Thanks a lot!
I did as your advice, and it works great!!!!!!!!!!!!!!!!

**Comment by eboasson** [comment]
☺️

For all of the points I mentioned ... they are all things that in my opinion have real value for the project, rather than simply hacks. So, if at some point you feel comfortable sharing some of the improvements you made, I'd be happy to look at them with an eye to merging them in.

**Comment by jwcesign** [comment]
I will try to think how to make that smaller and will check where can be good for the cyclonedds and commit. Thanks again!
