### ISSUE TITLE
Where is vortexddslauncher?

### ISSUE THREAD

**Issue by kartben** [eclipse/cyclonedds#3]
The documentation refers to the vortexddslauncher (and the presence of the launcher is also used by the fog05 config scripts, btw) but it looks likes this launcher is not part of Eclipse Cyclone DDS, or is it?

/cc @kydos

**Comment by michielb-adlink** [comment]
@kartben you're correct, at the moment the launcher is not part of Eclipse Cyclone DDS. It will be added in the future, but no time frame know yet.

**Comment by kartben** [comment]
@michielb-adlink Thanks for the answer. Could someone then look at fixing the documentation? It just sounds wrong to tell people to use something that just doesn't exist (yet?) :-)
Thanks!
