### ISSUE TITLE
How do use Cyclone DDS on Windows?

### ISSUE THREAD

**Issue by Boereck** [eclipse/cyclonedds#5]
Hi,

I was trying to do the build/install and then use Cyclone DDS on windows (using Visual Studio). I was able to configure cmake with the `Visual Studio 15 2017` generator and call 
`cmake --build . --config Release --target install` with admin rights from the build dir to install the CycloneDDS module. So far so good. Although it would be nice if the build steps for Windows / Visual Studio would be documented as well.

The actual problem I now am stuck with is, that the headers do not seem to be found when trying to use an example project. I copied the "helloworld" example project to a different location and just tried to configure and build it. Configuring the build with the `Visual Studio 15 2017` generator works, but actually building the project fails, because the ddsc headers cannot be resolved. Is there an INCLUDE_DIRS variable I can use or something?

I've uploaded the test project here:
https://github.com/Boereck/cyclone-dds-test
If you run the `init.ps1` powershell script on windows you should see that the last build step fails.

Thanks!

**Comment by ernstvanveenendaal** [comment]
Hi,

I've tried your project and am able to reproduce the issue. It seems the Visual Studio solution files generated by cmake are missing the path to the Cyclone DDS header files. 
When manual adding this path (C:\Program Files (x86)\CycloneDDS\include in my case) to the solution file using Visual Studio, I was able to build your project. This can be a temporary work-around, as it should work out-of-the box and is something we need to fix.

Regards,
Ernst

**Comment by Boereck** [comment]
Hey Ernst,

I've realized this as well. I am currently passing the include path as a variable to the CMake setup and then call `include_directories` with the variable in the CMake. This way I can simply not define the variable on Linux and the CmakeLists.txt can stay the same for both platforms. This will add the include to the Visual Studio solution, so I don't have to add it again if I have to delete my build folder (including the solution) for some reason. 
I can live with this workaround for now.

Thanks,
Max

**Comment by ernstvanveenendaal** [comment]
Hi Max,

Good to hear this work-around for you. As I think this issue should be solve, I would suggest to keep this issue open until it has been fixed properly.

Thanks,
Ernst

**Comment by eboasson** [comment]
I believe I fixed this (https://github.com/eclipse/cyclonedds/commit/6095b467d3407245127fbf58e4015c705f0b7a8e)

**Comment by Boereck** [comment]
I can confirm that the issue does occur anymore in our setup. Thanks for the quick fix!
